# Config file for SSHLogger
https://github.com/guldkage/SSHLogger

# Basic
webhook: "https://discord.com/api/webhooks/xxxxx" # Paste in your discord webhook
onReady: "I am ready to listen for SSH connections!"

# Webhook
webhookTitle: "WARNING: NEW SSH LOGIN"
webhookDescription: "A new successful login has just been detected! Please read this message carefully!"
webhookColor: 0x00ff00

# Webhook fields
userInfo: "Local account on server"
ipAddress: "Client IP address"
serverAffected: "Affected server"
affectedServerOS: "Server operating system"
clientGeolocation: "Client geolocation"

# Codes
journalctl: "Error running journalctl"
journalctlExit: "journalctl-processen exited with code"
unknownUser: "Unknown user"
unknownDevice: "Unknown device"
unknown: "Unknown"
ipAddressUnknown: "IP address not restrived"

geolocationFail: "Error retrieving geolocation"

embedSent: "Embed sent to Discord webhook"
embedError: "Error sending embed to Discord"
