# Config file for SSHLogger
# https://github.com/guldkage/SSHLogger

# Basic
webhook: "https://discord.com/api/webhooks/xxxxx"
onReady: "I am ready to listen for SSH connections!"

# Discord ping
# By default @everyone gets pinged, but that can be changed here. Examples:
# "<@DISCORD-ID>". This will only ping 1 member. Change this to your own discord ID.
# or you can ping a role: " <@&ROLE-ID>". Change this to your own role.
ping: "@everyone"

# Webhook
webhookTitle: "WARNING: NEW SSH LOGIN"
webhookDescription: "A new successful login has just been detected! Please read this message carefully!"
webhookColor: 16711680 # red

# Webhook fields
userInfo: "Local account on server"
ipAddress: "Client IP address"
serverAffected: "Affected server"
affectedServerOS: "Server operating system"
clientGeolocation: "Client geolocation"

# Error codes
journalctl: "Error running journalctl"
journalctlExit: "journalctl-process exited with code"
unknownUser: "Unknown user"
unknownDevice: "Unknown device"
unknown: "Unknown"
ipAddressUnknown: "IP address not restrived"

geolocationFail: "Error retrieving geolocation"

# Embed
embedSent: "Embed sent to Discord webhook"
embedError: "Error sending embed to Discord"
